name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - name: Install Packages
        run: npm install -f
      - name: Build
        run: npm run build
        env:
          SYNCKIT_TS_RUNNER: oxc
      - name: Lint
        run: npm run lint
      - name: tsc
        run: npm run tsc
      - name: load
        run: node lib/index.js
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install -f
      - name: Test
        run: |
          node -v
          echo $SYNCKIT_TS_RUNNER
          npm test
        env:
          SYNCKIT_TS_RUNNER: oxc
